image: alpine
stages:
  - compile
  - test
  - package
  - delpoy

compile:
  stage: compile
  script: cat file1.txt file2.txt > compiled.txt
  artifacts:
    paths:
    - compiled.txt
    expire_in: 20 minutes
    
test:
  stage: test
  script: egrep -w 'Hello|world' file1.txt file2.txt

package:
  stage: package
  script: cat compiled.txt | gzip > package.gz
  artifacts:
    paths:
    - package.gz

pack-iso:
  stage: package
  before_script:
  - echo "ipv6" >> /etc/modules
  - apk update
  - apk add xorriso
  script:
  - mkisofs -o ./package.iso ./compiled.txt
  artifacts:
    paths:
    - package.iso
    
delpoy:
  stage: delpoy
  before_script: 
  - apk add --no-cache openssh-client
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$admin_key_stockholm" >> ~/.ssh/admin_key_stockholm-vm
  - ls -la
  - cat ~/.ssh/admin_key_stockholm-vm
  - pwd
  script: ssh -T ec2-user@13.48.123.71 -i ~/.ssh/admin_key_stockholm-vm

    