image: alpine
stages:
  - compile
  - delpoy

compile:
  stage: compile
  script: cat file1.txt file2.txt > compiled.txt
  artifacts:
    paths:
    - compiled.txt
    
delpoy:
  stage: delpoy
  before_script: 
  - apk add --no-cache openssh-client
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo "$admin_key_stockholm" >> ~/.ssh/ssh_key
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod 600 ~/.ssh/ssh_key
  - ls -la
  script:
  - scp -i ~/.ssh/ssh_key compiled.txt ec2-user@13.48.123.71:/files/
  - ssh -T ec2-user@13.48.123.71 -i ~/.ssh/ssh_key "mkdir gitlab"


    