image: alpine
stages:
  - compile
  - test
  - package
  - delpoy

compile:
  stage: compile
  script: cat file1.txt file2.txt > compiled.txt
  artifacts:
    paths:
    - compiled.txt
    expire_in: 20 minutes
    
test:
  stage: test
  script: egrep -w 'Hello|world' file1.txt file2.txt

package:
  stage: package
  script: cat compiled.txt | gzip > package.gz
  artifacts:
    paths:
    - package.gz

pack-iso:
  stage: package
  before_script:
  - echo "ipv6" >> /etc/modules
  - apk update
  - apk add xorriso
  script:
  - mkisofs -o ./package.iso ./compiled.txt
  artifacts:
    paths:
    - package.iso
    
delpoy:
  stage: delpoy
  before_script: 
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$admin_key_stockholm" >> admin_key_stockholm-vm
  - chmod 700 admin_key_stockholm-vm
  script: ssh ec2-user@13.48.123.71 -i admin_key_stockholm-vm

    