image: alpine
stages:
  - compile
  - delpoy

compile:
  stage: compile
  script: cat file1.txt file2.txt > compiled.txt
  artifacts:
    paths:
    - compiled.txt
    
delpoy:
  stage: delpoy
  before_script: 
  - apk add --no-cache openssh-client
  - eval $(ssh-agent -s)
  - echo "$admin_key_stockholm" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  script: ssh -T ec2-user@13.48.123.71

    