image: alpine
stages:
  - compile
  - delpoy

compile:
  stage: compile
  script: cat file1.txt file2.txt > compiled.txt
  artifacts:
    paths:
    - compiled.txt
    
delpoy:
  stage: delpoy
  before_script: 
  - apk add --no-cache openssh-client
  - eval $(ssh-agent -s)
  - mkdir -p .ssh
  - echo "$admin_key_stockholm" >> .ssh/admin_key_stockholm-vm
  - chmod 700 .ssh/admin_key_stockholm-vm
  - ssh-keyscan -t rsa 13.48.123.71 >> .ssh/known_hosts
  - ls -la
  script: ssh -T ec2-user@13.48.123.71 -i .ssh/admin_key_stockholm-vm

    