image: alpine
stages:
  - compile
  - test
  - package

compile:
  stage: compile
  script: cat file1.txt file2.txt > compiled.txt
  artifacts:
    paths:
    - compiled.txt
    expire_in: 20 minutes
    
test:
  stage: test
  script: egrep -w 'Hello|world' file1.txt file2.txt

package:
  stage: package
  script: cat compiled.txt | gzip > package.gz
  artifacts:
    paths:
    - package.gz